-- =========================
-- ENUM TYPES
-- =========================

create type pronouns as enum (
'he_him',
'she_her',
'they_them'
);

create type sexual_pref as enum (
'straight',
'gay',
'bisexual',
'pansexual'
);

create type gender as enum (
'male',
'female',
'non_binary',
'mtf',
'ftm'
);

create type body_type as enum (
'slim',
'average',
'large',
'muscular'
);

create type relationship_status as enum (
'single',
'taken',
'married'
);

create type ethnicity as enum (
'asian',
'black',
'white',
'latino',
'middle_eastern',
'mixed',
'native_american',
'south_asian'
);

create type interests as enum (
'cars',
'music',
'art',
'movie',
'nature',
'gaming',
'drinking',
'smoking',
'gym',
'partying',
'swimming',
'sports',
'education',
'singing',
'photography',
'writing',
'programming',
'instruments',
'books_reading'
);

create type job_type as enum (
'programmer',
'security',
'actor',
'retail',
'business',
'entertainer',
'athlete',
'gamer',
'police',
'medical',
'military'
);

create type zodiac as enum (
'capricorn',
'aquarius',
'pisces',
'aries',
'taurus',
'gemini',
'cancer',
'leo',
'virgo',
'libra',
'scorpio',
'sagittarius'
);

create type language_type as enum (
'english',
'spanish',
'french',
'german',
'chinese',
'japanese',
'russian',
'italian',
'hebrew',
'asl',
'other'
);

create type color_type as enum (
'black',
'white',
'red',
'orange',
'yellow',
'green',
'blue',
'purple',
'grey',
'brown'
);

create type nationality as enum (
'british',
'american',
'german',
'french',
'mexican',
'canadian',
'chinese',
'japanese',
'polish',
'russian',
'brazilian',
'cuban',
'other'
);

create type education_type as enum (
'none',
'diploma',
'associates',
'bachelors',
'masters',
'phd'
);

create type cosmetics as enum (
'none',
'makeup',
'scars',
'piercings',
'freckles',
'facial_hair'
);

create type social_platform as enum (
'discord',
'facebook',
'instagram',
'whatsapp',
'messenger',
'twitter',
'snapchat'
);

create type living_status as enum (
'homeless',
'alone',
'parents',
'family'
);

create type day_type as enum (
'mon',
'tue',
'wed',
'thur',
'fri',
'sat',
'sun'
);

create type mbti as enum (
'intj','intp','entj','entp',
'infj','infp','enfj','enfp',
'istj','isfj','esfj','estj',
'istp','isfp','estp','esfp'
);

-- =========================
-- USER TABLE
-- =========================

create table public.user_data (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),

    user_id text unique,

    name text default 'NoName',
    age smallint default 0,

    location double precision,
    height real,
    weight integer,

    -- ENUM ARRAYS (multiple values allowed)
    interests interests[],
    languages language_type[],
    socials social_platform[],
    availability day_type[],

    -- Single-value enums
    job job_type,

    glasses boolean default false,
    kids boolean,
    pets boolean,
    drives boolean,

    sexual_pref sexual_pref,
    pronouns pronouns,
    gender gender,

    living living_status,
    zodiac zodiac,
    education education_type,

    hair_color color_type,
    eye_color color_type,

    race ethnicity,
    body_modification cosmetics,
    body body_type,

    nationality nationality,
    relationship relationship_status,

    is_complete boolean default false,
    compatibility_score real default 0.0,

    seeking_gender text default 'everyone',
    max_distance_km integer default 50,

    mbti mbti
);

-- =========================
-- INDEXES
-- =========================

create index if not exists user_data_user_id_idx
on public.user_data(user_id);

create index if not exists user_data_complete_idx
on public.user_data(is_complete)
where is_complete = true;
